version: '2'
services:
    jurisfacile-app:
        image: jurisfacile
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jurisfacile-mysql:3306/jurisfacile?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jurisfacile-mysql:
        extends:
            file: mysql.yml
            service: jurisfacile-mysql
